spring.application.name=demo

# Configuración de la Base de Datos (Conectando al contenedor local)
spring.datasource.url=jdbc:postgresql://localhost:5432/monit_db
spring.datasource.username=postgres
spring.datasource.password=tu_contrasena_segura
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate / JPA
# 'update' creará las tablas automáticamente en la base de datos cuando definamos entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true